### ISSUE TITLE
LinearRoad dataset and benchmark failure

### ISSUE THREAD

**Issue by cyrus-and** [ShuhaoZhangTony/briskstream#10]
I'm generating the dataset with [`LinearGenerator`][1] and placing the resulting file in `~/data/app/lr/cardatapoints-combine.out` yet the Storm and Flink benchmarks fail for no apparent reason and the `metric_output` directory is not populated. Other applications work, e.g., `WordCount`.

Is that generator compatible with this test suite?

I can provide additional details if needed. Any hint will be greatly appreciated.

[1]: https://github.com/walmartlabs/LinearGenerator

**Comment by ShuhaoZhangTony** [comment]
I use dataset generator from here: (http://www.it.uu.se/research/group/udbl/lr.html)

I guess it should be fine as long as the generator keeps the same dataformat.
Don't forget the **historical-tolls.out** file.

**Comment by cyrus-and** [comment]
Thanks for your reply, I tried that generator but it was super hard to make it work correctly as it needed a 32bit VM and a few other precautions, plus it appears to be quite slow compared to the one linked above. In any case no exception in the log seems related to wrong/unexpected dataset files.

The two resulting files are as follows:

```console
user@a2e2fcf905da:~/briskstream$ head /home/user/data/app/lr/cardatapoints-combine.out 
0,0,0,10,0,0,0,56,295680,-1,-1,-1,-1,-1,-1
0,0,1,10,0,0,1,26,142559,-1,-1,-1,-1,-1,-1
2,0,1,10,0,0,1,26,142559,0,-1,-1,-1,-1,-1
0,0,2,10,0,0,1,38,205919,-1,-1,-1,-1,-1,-1
0,0,3,10,0,0,1,82,438239,-1,-1,-1,-1,-1,-1
0,0,4,10,0,0,1,50,269279,-1,-1,-1,-1,-1,-1
0,0,5,10,0,0,0,17,89760,-1,-1,-1,-1,-1,-1
0,0,6,10,0,0,1,83,443519,-1,-1,-1,-1,-1,-1
0,0,7,10,0,0,0,8,42240,-1,-1,-1,-1,-1,-1
0,0,8,10,0,0,1,53,285119,-1,-1,-1,-1,-1,-1
user@a2e2fcf905da:~/briskstream$ head /home/user/data/app/lr/historical-tolls.out
0,1,0,96
0,2,0,25
0,3,0,37
0,4,0,70
0,5,0,17
0,6,0,75
0,7,0,39
0,8,0,85
0,9,0,50
0,10,0,86
```

For example with Flink I run the benchmark with:

```
java -cp FlinkBenchmarks/target/Flink-1.3.2-jar-with-dependencies.jar applications.FlinkRunner -a LinearRoad -tt 1
```

And besides a bunch of `java.lang.Exception: The JobManager is shutting down.` there are *sometimes* :

```
java.lang.IllegalStateException: Memory manager has been shut down.
        at org.apache.flink.runtime.memory.MemoryManager.releaseAll(MemoryManager.java:475)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:823)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

and:

```
java.lang.RuntimeException: Buffer pool is destroyed.
        at org.apache.flink.streaming.runtime.io.RecordWriterOutput.emitLatencyMarker(RecordWriterOutput.java:140)
        at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.emitLatencyMarker(AbstractStreamOperator.java:885)
        at org.apache.flink.streaming.api.operators.StreamSource$LatencyMarksEmitter$1.onProcessingTime(StreamSource.java:151)
        at org.apache.flink.streaming.runtime.tasks.SystemProcessingTimeService$RepeatedTriggerTask.run(SystemProcessingTimeService.java:255)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Buffer pool is destroyed.
        at org.apache.flink.runtime.io.network.buffer.LocalBufferPool.requestBuffer(LocalBufferPool.java:205)
        at org.apache.flink.runtime.io.network.buffer.LocalBufferPool.requestBufferBlocking(LocalBufferPool.java:193)
        at org.apache.flink.runtime.io.network.api.writer.RecordWriter.sendToTarget(RecordWriter.java:132)
        at org.apache.flink.runtime.io.network.api.writer.RecordWriter.randomEmit(RecordWriter.java:107)
        at org.apache.flink.streaming.runtime.io.StreamRecordWriter.randomEmit(StreamRecordWriter.java:103)
        at org.apache.flink.streaming.runtime.io.RecordWriterOutput.emitLatencyMarker(RecordWriterOutput.java:137)
        ... 9 more
```

Find the whole log [here][1].

[1]: https://gist.githubusercontent.com/cyrus-and/230f00eba7208f605c83f190d3ecc80a/raw/828b379b76123fc821fda209cc713a0255895dc0/log

**Comment by ShuhaoZhangTony** [comment]
I think it's caused by "," in your datasets. 
I used " " as the delimiter, see Line 57 DispatcherBolt.java. Too bad, it's hardcoded...

**Comment by cyrus-and** [comment]
> I think it's caused by "," in your datasets. I used " " as the delimiter

I can easily change the datasets, thank you.

> see Line 57 DispatcherBolt.java

If I place a breakpoint there though it never stops and FWIW neither one on the `nextTuple` of the spout. So there must me another problem here...

Just to be clear (for what concerns the spout), this is executed:

https://github.com/Xtra-Computing/briskstream/blob/506aefb9e41490785be1e659779220df5401854f/FlinkBenchmarks/src/main/java/applications/spout/MemFileSpout.java#L52

While this is never executed:

https://github.com/Xtra-Computing/briskstream/blob/506aefb9e41490785be1e659779220df5401854f/FlinkBenchmarks/src/main/java/applications/spout/MemFileSpout.java#L221-L223

**Comment by cyrus-and** [comment]
FYI, I obtain the same behavior even using the dataset generated by [this](https://www.cs.brandeis.edu/~linearroad/tools.html) (the original) tool.

**Comment by cyrus-and** [comment]
> Don't forget the **historical-tolls.out** file.

AFAICT that file is only used by the `DailyExpenditureBolt` class, and that class is not part of the topology, can you explain why is that?

https://github.com/Xtra-Computing/briskstream/blob/506aefb9e41490785be1e659779220df5401854f/StormBenchmarks/src/main/java/applications/bolts/lr/DailyExpenditureBolt.java#L105-L109

**Comment by cyrus-and** [comment]
On a similar note I noticed that in the [`DispatcherBolt`][1] the emit of the tuple types other than 0 are commented out, this could explain why several bolts are not used in the topology as the one I mentioned above... but why is that?

I tried to sketch by hand the graph from the [`buildTopology`][2] method of the `LinearRoad` Storm class and if I'm not mistaken the result is the following:

![lr](https://user-images.githubusercontent.com/1660263/68794146-b7dab180-064e-11ea-9e87-2133c673b202.png)

This is quite different from the one present in your paper "BriskStream: Scaling Data Stream Processing on Shared-Memory Multicore Architectures" (Fig. 18 (c)). I understand that splitting the toll notification node could be an architectural choice but what about the "accident detection" and "accident notification" nodes that appear to be dangling according to the above picture?

[1]: https://github.com/Xtra-Computing/briskstream/blob/506aefb9e41490785be1e659779220df5401854f/StormBenchmarks/src/main/java/applications/bolts/lr/DispatcherBolt.java#L62
[2]: https://github.com/Xtra-Computing/briskstream/blob/506aefb9e41490785be1e659779220df5401854f/StormBenchmarks/src/main/java/applications/topology/benchmarks/LinearRoad.java#L57

---

I understand that I'm basically spamming you and that I've brought up many points... I'm sorry about that. :) We just need to understand those details in order to be able to use and reference your research. I hope you can find the time to address each point above, thanks for your patience.

**Comment by ShuhaoZhangTony** [comment]
right, the input dataset I have been used contains very minor portion of different data types other than the position report. 
That is to say, operators (AD and AN) that only consumes input types like accident report will almost **never** get executed. For simplicity, I comment out them in my later experiments. You can re-enable them for sure.

**Comment by ShuhaoZhangTony** [comment]
To debug, I suggest you comment out some operators first. Say, only leave the application with _Spout_ and _Sink_. If it runs, then you gradually add more operators, Spout->Bolt->Sink. 
The problem is that, I have hardcoded some codes (e.g., the delimiter) here and there for my own convenience. It's hard for me to understand what has caused the problem in your setting. Unfortunately, I have no capacity to improve them at the current stage..

**Comment by cyrus-and** [comment]
Understood, thanks.

Did you use the current version in the aforementioned paper? That is, the one with position reports types only.

**Comment by ShuhaoZhangTony** [comment]
I used the full version in the SIGMOD19 although there should not be any differences.

I have subsequent works that I have significantly simplified the application in order to focus on other key aspects, but the work is currently under review. You can add my skype shzhang1@e.ntu.edu.sg if you want to have a further discussion regarding it. I'm open for research collaboration too.

**Comment by cyrus-and** [comment]
I see, it does make sense. I will reach out to you on Skype if I need clarification about that and update this issue if I come up to a solution. Thank you.
